### ISSUE TITLE
`_create_section` adds a PageBreakItem and SectionHeaderItem is not implemented

### ISSUE THREAD

**Issue by jeLee6gi** [george-gca/markdown-to-google-forms#2]
I expected `_create_section` to implement `https://developers.google.com/apps-script/reference/forms/section-header-item`. 

Maybe you want to add `_create_page_break` for `https://developers.google.com/apps-script/reference/forms/page-break-item`?

**Comment by george-gca** [comment]
I did this based on how the Google Forms works from a UI point of view. For instance, when creating a Google Forms on the web you don't add a page break, you create a new Section, and it internally creates (I think) a page break and a section.

**Comment by jeLee6gi** [comment]
Ok I'm not sure about the most appropriate naming either but I was missing a way to add what's called "Add title and description" in the UI which I am actually using in my forms to add additional context in places.

**Comment by george-gca** [comment]
Hummm now I get it. I can add the `Add title and description` regex. Maybe if the markdown only have something like this:

```markdown
### Title

Description
```

What do you think?

**Comment by jeLee6gi** [comment]
Sounds good, that should work and it complements your syntax for sections nicely

**Comment by george-gca** [comment]
And I just confirmed my suspicious [here](https://stackoverflow.com/a/64277961/14459430). Anyway, just implemented it and will upload it in a few minutes.

**Comment by george-gca** [comment]
Just implemented this.
